from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


class SlideSpec(BaseModel):
    """Structured slide specification generated by LLM."""

    title: str = Field(min_length=1)
    subtitle: str | None = None
    bullets: list[str] = Field(default_factory=list, max_length=8)
    notes: str | None = None
    visual_hint: str | None = Field(
        default=None,
        description="Hint for future image/chart generation modules.",
    )
    section: str | None = Field(
        default=None,
        description="Narrative section label such as 背景 / 分析 / 策略 / 落地.",
    )
    layout: Literal["title", "title_and_content", "section", "comparison"] = "title_and_content"

    @field_validator("bullets")
    @classmethod
    def validate_bullets(cls, bullets: list[str]) -> list[str]:
        cleaned = [item.strip() for item in bullets if item.strip()]
        if len(cleaned) > 8:
            raise ValueError("Each slide supports at most 8 bullet points.")
        return cleaned


class DeckOutline(BaseModel):
    """Complete deck plan for rendering."""

    topic: str = Field(min_length=1)
    audience: str = Field(default="general")
    language: str = Field(default="zh-CN")
    style: Literal["executive", "educational", "marketing", "technical"] = "executive"
    template: Literal["consulting", "modern", "minimal"] = "consulting"
    background: Literal["light", "dark", "gradient"] = "light"
    theme_color: str | None = Field(
        default=None,
        description="Optional brand color in #RRGGBB format used as global accent.",
    )
    content_outline: list[str] = Field(
        default_factory=list,
        description="Optional user-defined storyline constraints for the planner.",
    )
    narrative_flow: list[str] = Field(
        default_factory=lambda: ["开场", "现状", "问题", "方案", "实施", "结论"],
        description="Deck-level storyline to keep slide progression continuous.",
    )
    slides: list[SlideSpec] = Field(min_length=3, max_length=30)

    @field_validator("theme_color")
    @classmethod
    def validate_theme_color(cls, color: str | None) -> str | None:
        if color is None:
            return None
        normalized = color.strip().upper()
        if normalized.startswith("#"):
            normalized = normalized[1:]
        if len(normalized) != 6 or any(ch not in "0123456789ABCDEF" for ch in normalized):
            raise ValueError("theme_color must be a hex color like #3B82F6")
        return f"#{normalized}"

    @field_validator("content_outline")
    @classmethod
    def validate_content_outline(cls, items: list[str]) -> list[str]:
        return [item.strip() for item in items if item.strip()]
